version: "3"
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hts
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
